version: '3'

services: 
  db:
    # image: mariadb:10.3
    # docker run -v mysql_data_ci:/var/lib/mysql
    build: 
      dockerfile: Dockerfile
      context: ./db/
    volumes:
      - mysql_data_ci:/var/lib/mysql
      #- ./db/dump.sql:/docker-entrypoint-initdb.d/setup.sql
    # docker run --network ci_cetwork
    networks:
      - ci_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      #docker run -e MYSQL_ROOT_PASSWORD=1111
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    networks:
      - ci_network
    restart: always
  codeigniter:
    depends_on:
      - db
    build: 
      dockerfile: Dockerfile
      context: ./
    networks:
      - ci_network
    ports:
      - 8080:80
    restart: always
    volumes:
      - $PWD:/var/www/html
    
volumes:
  mysql_data_ci:

networks: 
  ci_network: